### ISSUE TITLE
INFO -- : Completed 500 Internal Server Error in 15ms (ActiveRecord: 0.1ms | Allocations: 7130)

### ISSUE THREAD

**Issue by dcalixto** [alxlion/eyeloupe#4]
Hello, someone has any idea why this is happening?

![ey1](https://github.com/alxlion/eyeloupe/assets/1009077/3414431e-9e29-4e0f-8578-9e9fed1cb4a7)
![ey2](https://github.com/alxlion/eyeloupe/assets/1009077/e2ac9d8c-a089-4af0-b0f7-c2605f532ae8)

**Comment by dcalixto** [comment]
I deleted the initializer and now this is :
`NoMethodError - undefined method `turbo_frame_tag' for #<ActionView::Base:0x00000000015d88`>:

![turbo](https://github.com/alxlion/eyeloupe/assets/1009077/8b68990b-0adb-4529-9159-80f86bb6c9c5)
![turbo2](https://github.com/alxlion/eyeloupe/assets/1009077/28ddeafd-779b-4183-be93-0e8ee1e93a6e)


i use sprockets, i need to install turbo?

**Comment by alxlion** [comment]
Yes it needs turbo to work
